import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: "#fff", padding: 16 },
  header: { marginBottom: 16 },
  title: { fontSize: 24, fontWeight: "700", marginBottom: 4 },
  subtitle: { color: "#666", marginBottom: 8 },
  addButton: { backgroundColor: "#4f46e5", padding: 10, borderRadius: 8, alignSelf: "flex-start", marginBottom: 12 },
  addButtonText: { color: "#fff", fontWeight: "700" },
  statsGrid: { flexDirection: "row", flexWrap: "wrap", justifyContent: "space-between", marginBottom: 16 },
  statCard: { width: "32%", backgroundColor: "#f9f9f9", padding: 12, borderRadius: 12, marginBottom: 12 },
  statTitle: { fontSize: 14, fontWeight: "600" },
  statValue: { fontSize: 18, fontWeight: "700", marginTop: 4 },
  card: { borderWidth: 1, borderColor: "#ddd", borderRadius: 12, padding: 12, marginBottom: 16 },
  cardTitle: { fontSize: 18, fontWeight: "700", marginBottom: 8 },
  serviceItem: { flexDirection: "row", justifyContent: "space-between", padding: 12, borderWidth: 1, borderColor: "#eee", borderRadius: 12, marginBottom: 8 },
  serviceHeader: { flexDirection: "row", alignItems: "center", marginBottom: 4 },
  clientName: { fontWeight: "500", marginRight: 6 },
  petBadge: { backgroundColor: "#ddd", paddingHorizontal: 6, paddingVertical: 2, borderRadius: 6 },
  petText: { fontSize: 12 },
  serviceDetails: { flexDirection: "row", alignItems: "center", gap: 8 },
  dateText: { fontSize: 12, color: "#666", marginRight: 8 },
  typeBadge: { paddingHorizontal: 6, paddingVertical: 2, borderRadius: 6, marginRight: 8 },
  typeText: { fontSize: 12 },
  valueText: { fontWeight: "500", fontSize: 12 },
  statusContainer: { justifyContent: "center", alignItems: "center", marginLeft: 8 },
  statusBadge: { paddingHorizontal: 8, paddingVertical: 4, borderRadius: 6, marginBottom: 4 },
  statusText: { fontSize: 12, color: "#fff", fontWeight: "600" },
  editButton: { borderWidth: 1, borderColor: "#4f46e5", paddingHorizontal: 8, paddingVertical: 4, borderRadius: 6 },
  editButtonText: { fontSize: 12, color: "#4f46e5", fontWeight: "600" },
});